In [4]:
import pandas as pd
import os
import cv2
from ultralytics import YOLO
import yaml
from sklearn.model_selection import train_test_split
import shutil
import random


class LesionTzetlinTrainer:
    def __init__(
        self,
        base_images_dir="data/Dataset-pruned/base_images",
        lesion_data_path="data/Dataset-pruned/lesion_data.csv",
    ):
        self.base_images_dir = base_images_dir
        self.lesion_data_path = lesion_data_path
        self.dataset_dir = "yolo_dataset"
        self.lesion_df = None

    def load_data(self):
        print("Loading lesion data...")
        self.lesion_df = pd.read_csv(self.lesion_data_path)
        print(f"Loaded {len(self.lesion_df)} lesion annotations")

    def create_dataset_structure(self):
        print("Creating dataset structure...")

        for split in ["train", "val"]:
            os.makedirs(f"{self.dataset_dir}/{split}/images", exist_ok=True)
            os.makedirs(f"{self.dataset_dir}/{split}/labels", exist_ok=True)

    def convert_to_yolo_format(self, x, y, width, height, img_width, img_height):
        center_x = x + width / 2
        center_y = y + height / 2

        norm_center_x = center_x / img_width
        norm_center_y = center_y / img_height
        norm_width = width / img_width
        norm_height = height / img_height

        return norm_center_x, norm_center_y, norm_width, norm_height

    def process_annotations(self):
        print("Processing annotations...")

        grouped = self.lesion_df.groupby(["image_id", "frame"])

        image_annotations = {}

        for (image_id, frame), group in grouped:
            image_filename = f"{image_id}_{frame}.png"
            image_path = os.path.join(self.base_images_dir, image_filename)

            if not os.path.exists(image_path):
                print(f"WARNING: Image {image_filename} not found, skipping...")
                continue

            img = cv2.imread(image_path)
            if img is None:
                print(
                    f"WARNING: Image exists, but cannot be loaded {image_filename}, skipping..."
                )
                continue

            img_height, img_width = img.shape[:2]

            annotations = []
            for _, row in group.iterrows():
                x = row["lesion_x"]
                y = row["lesion_y"]
                width = row["lesion_width"]
                height = row["lesion_height"]

                if (
                    pd.isna(row["lesion_x"])
                    or pd.isna(row["lesion_y"])
                    or pd.isna(row["lesion_width"])
                    or pd.isna(row["lesion_height"])
                ):
                    continue

                norm_cx, norm_cy, norm_w, norm_h = self.convert_to_yolo_format(
                    x, y, width, height, img_width, img_height
                )

                if not (
                    0 <= norm_cx <= 1
                    and 0 <= norm_cy <= 1
                    and 0 <= norm_w <= 1
                    and 0 <= norm_h <= 1
                ):
                    print(
                        f"WARNING: Invalid normalized coordinates for {image_filename}: cx={norm_cx}, cy={norm_cy}, w={norm_w}, h={norm_h}"
                    )
                    continue

                annotations.append(
                    f"0 {norm_cx:.6f} {norm_cy:.6f} {norm_w:.6f} {norm_h:.6f}"
                )

            image_annotations[image_filename] = annotations

        return image_annotations

    def split_dataset(self, image_annotations, train_ratio=0.8):
        print("Splitting dataset...")

        image_files = list(image_annotations.keys())
        train_files, val_files = train_test_split(
            image_files, train_size=train_ratio, random_state=42
        )

        print(f"Training images: {len(train_files)}")
        print(f"Validation images: {len(val_files)}")

        return train_files, val_files

    def copy_files_and_create_labels(self, image_annotations, train_files, val_files):
        print("Copying files and creating labels...")

        for split, files in [("train", train_files), ("val", val_files)]:
            for image_file in files:
                src_image = os.path.join(self.base_images_dir, image_file)
                dst_image = os.path.join(self.dataset_dir, split, "images", image_file)
                shutil.copy2(src_image, dst_image)

                label_file = image_file.replace(".png", ".txt")
                label_path = os.path.join(self.dataset_dir, split, "labels", label_file)

                with open(label_path, "w") as f:
                    for annotation in image_annotations[image_file]:
                        f.write(annotation + "\n")

    def create_yaml_config(self):
        config = {
            "path": os.path.abspath(self.dataset_dir),
            "train": "train/images",
            "val": "val/images",
            "nc": 1,
            "names": ["lesion"],
        }

        config_path = os.path.join(self.dataset_dir, "dataset.yaml")
        with open(config_path, "w") as f:
            yaml.dump(config, f, default_flow_style=False)

        print(f"Created YAML config at {config_path}")
        return config_path

    def prepare_dataset(self):
        self.load_data()
        self.create_dataset_structure()

        image_annotations = self.process_annotations()
        train_files, val_files = self.split_dataset(image_annotations)
        self.train_files, self.val_files = train_files, val_files
        self.copy_files_and_create_labels(image_annotations, train_files, val_files)

        config_path = self.create_yaml_config()
        return config_path

    

    def train_model(self, config_path, model_size, epochs, imgsz=512):
        print(f"Starting YOLO training with {model_size}...")

        model = YOLO(f"{model_size}.pt")
        results = model.train(
            data=config_path,
            epochs=epochs,
            imgsz=imgsz,
            patience=50,
            save=True,
            # device="CUDA",
            device="0,1",
            # workers=4,
            batch=16,
            # batch=96,
            name="lesion_detection",
            exist_ok=True,
            single_cls=True,
            mosaic=0.0,
            mixup=0.0,
            degrees=15.0,
            flipud=0.5,
            fliplr=0.5,
        )

        print("Training completed!")
        return model, results

    def evaluate_model(self, model, dataset_yaml_path=None):
        print("Evaluating model...")

        metrics = model.val(data=dataset_yaml_path)

        print("\n=== Model Evaluation Results ===")
        print(f"mAP@0.5: {metrics.box.map50:.4f}")
        print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
        print(f"mAP@0.75: {metrics.box.map75:.4f}")
        print(f"Mean Precision: {metrics.box.mp:.4f}")
        print(f"Mean Recall: {metrics.box.mr:.4f}")

        return metrics

    def predict_sample(self, model, image_path, conf_threshold=0.25):
        print(f"Making prediction on {image_path}...")

        results = model.predict(
            image_path,
            conf=conf_threshold,
            save=True,
            show_labels=True,
            show_conf=True,
        )

        return results

    def predict_multiple_samples(self, model, num_samples=10, conf_threshold=0.1):
        print(f"Making predictions on {num_samples} sample images...")

        sample_images = os.listdir(self.base_images_dir)
        if not sample_images:
            print("No images found in base directory")
            return []

        random.seed(42)
        random.shuffle(sample_images)
        selected_samples = sample_images[: min(num_samples, len(sample_images))]

        image_paths = [
            os.path.join(self.base_images_dir, img) for img in selected_samples
        ]

        print(f"Selected images: {selected_samples}")

        try:
            results = model.predict(
                image_paths,
                conf=conf_threshold,
                save=True,
                show_conf=True,
                show_labels=True,
                visualize=True,
            )

            prediction_results = []
            for i, (image_file, result) in enumerate(zip(selected_samples, results)):
                num_detections = len(result.boxes) if result.boxes is not None else 0

                prediction_info = {
                    "image_file": image_file,
                    "image_path": image_paths[i],
                    "results": result,
                    "num_detections": num_detections,
                }

                prediction_results.append(prediction_info)
            return prediction_results

        except Exception as e:
            print(f"ERROR: batch prediction: {e}")
            return []


def evaluate_trained_model():
    trainer = LesionTzetlinTrainer(
        base_images_dir="./Dataset-pruned/base_images",
        lesion_data_path="./Dataset-pruned/lesion_data.csv",
    )

    trained_model_path = (
        "results/iteration-5/runs/detect/lesion_detection/weights/best.pt"
    )
    dataset_yaml_path = "results/iteration-5/yolo_dataset/dataset.yaml"

    if not os.path.exists(trained_model_path):
        print(f"ERROR: Trained model not found at {trained_model_path}")
        return

    if not os.path.exists(dataset_yaml_path):
        print(f"ERROR: Dataset YAML not found at {dataset_yaml_path}")
        return

    model = YOLO(trained_model_path)

    metrics = trainer.evaluate_model(model, dataset_yaml_path)
    print(f"Evaluation completed. mAP@0.5: {metrics.box.map50:.4f}")

    prediction_results = trainer.predict_multiple_samples(
        model, num_samples=30, conf_threshold=0.1
    )

    print(f"\nPredictions generated for {len(prediction_results)} images.")
    for i, pred_info in enumerate(prediction_results):
        print(
            f"  Image {i+1}: {pred_info['image_file']} - Detections: {pred_info['num_detections']}"
        )


def train_model():
    trainer = LesionTzetlinTrainer()
    config_path = trainer.prepare_dataset()

    # Models:
    # yolov8n -> nano version
    # yolov8s -> small version
    # yolov8m -> medium version
    # yolov8l -> large version
    # yolov8x -> extra large version
    model, results = trainer.train_model(
        config_path=config_path,
        model_size="yolo11l",
        epochs=300,
        imgsz=512,
    )

    metrics = trainer.evaluate_model(model)
    prediction_results = trainer.predict_multiple_samples(model, num_samples=10)

    print(f"Model saved")

In [ ]:
tzetlin_trainer = LesionTzetlinTrainer()

In [ ]:
tzetlin_trainer.train_model()

TypeError: LesionTzetlinTrainer.train_model() missing 3 required positional arguments: 'config_path', 'model_size', and 'epochs'

In [ ]:
config_path = tzetlin_trainer.prepare_dataset()

Loading lesion data...
Loaded 1061 lesion annotations
Creating dataset structure...
Processing annotations...
Splitting dataset...
Training images: 663
Validation images: 166
Copying files and creating labels...
Created YAML config at yolo_dataset/dataset.yaml


In [ ]:
config_path

'yolo_dataset/dataset.yaml'

In [ ]:
from keras.datasets import mnist

2025-09-22 20:49:33.088113: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-22 20:49:33.088754: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-22 20:49:33.154876: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-22 20:49:35.060677: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation or

In [ ]:
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [ ]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(60000, 784))

In [1]:
from pyTsetlinMachine.tm import MultiClassTsetlinMachine
import numpy as np

In [ ]:
np.where(X_train > 0)

(array([    0,     0,     0, ..., 59999, 59999, 59999], shape=(8994156,)),
 array([ 5,  5,  5, ..., 24, 24, 24], shape=(8994156,)),
 array([12, 13, 14, ...,  8,  9, 10], shape=(8994156,)))

In [ ]:
X_train.shape

(60000, 28, 28)

In [ ]:
X_train.reshape((X_train.shape[0], 28*28))

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(60000, 784), dtype=uint8)

In [ ]:
np.where(X_train.reshape((X_train.shape[0], 28*28)) > 75, 1, 0) 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(60000, 784))

In [ ]:
X_train = np.where(X_train.reshape((X_train.shape[0], 28*28)) > 75, 1, 0) 
X_test = np.where(X_test.reshape((X_test.shape[0], 28*28)) > 75, 1, 0) 

tm = MultiClassTsetlinMachine(2000, 50, 10.0)
tm

In [ ]:
tm

In [ ]:
from pyTsetlinMachine.tm import MultiClassTsetlinMachine
import numpy as np
from time import time

from keras.datasets import mnist

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

X_train = np.where(X_train.reshape((X_train.shape[0], 28*28)) > 75, 1, 0) 
X_test = np.where(X_test.reshape((X_test.shape[0], 28*28)) > 75, 1, 0) 

tm = MultiClassTsetlinMachine(2000, 50, 10.0)

print("\nAccuracy over 250 epochs:\n")
for i in range(2):
	start_training = time()
	tm.fit(X_train, Y_train, epochs=1, incremental=True)
	stop_training = time()

	start_testing = time()
	result = 100*(tm.predict(X_test) == Y_test).mean()
	stop_testing = time()

	print("#%d Accuracy: %.2f%% Training: %.2fs Testing: %.2fs" % (i+1, result, stop_training-start_training, stop_testing-start_testing))


Accuracy over 250 epochs:

#1 Accuracy: 93.98% Training: 31.66s Testing: 3.14s
#2 Accuracy: 94.99% Training: 17.14s Testing: 3.08s


In [ ]:
tm.predict(X_test[:10])

array([7, 2, 1, 0, 4, 1, 4, 9, 6, 9], dtype=uint32)

In [ ]:
result

np.float64(94.99)

In [ ]:
1*(tm.predict(X_test) == Y_test).mean()*100

np.float64(94.99)

In [ ]:
import numpy as np

In [ ]:
img0_path = filenames[0]
img0_path

'data/Dataset-pruned/base_images/131aedfhs6pnf1fvtvp49mldx9653nxv22_45.png'

In [5]:
# tsetlin_train.py
import os
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from pyTsetlinMachine.tm import MultiClassConvolutionalTsetlinMachine2D
from time import time

def load_image_folder(folder, size=(28,28), threshold=128):
    X = []
    y = []
    classes = sorted(os.listdir(folder))
    class_to_idx = {c:i for i,c in enumerate(classes)}
    for c in classes:
        class_dir = os.path.join(folder, c)
        if not os.path.isdir(class_dir):
            continue
        for fname in os.listdir(class_dir):
            print(fname)
            if not fname.lower().endswith((".png", ".jpg", ".jpeg", ".bmp")):
                continue
            path = os.path.join(class_dir, fname)
            img = Image.open(path).convert("L")          # grayscale
            img = img.resize(size, Image.NEAREST)       # resize
            arr = np.array(img)                         # shape (H,W)
            # binarize
            bin_arr = (arr >= threshold).astype(np.uint8)
            X.append(bin_arr)
            y.append(class_to_idx[c])
    X = np.stack(X)   # shape (N, H, W)
    y = np.array(y, dtype=np.int32)
    return X, y, class_to_idx

In [ ]:
X_train[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 

In [7]:
tzetlin_trainer = LesionTzetlinTrainer()

In [ ]:
def load_images

In [8]:
image_paths = tzetlin_trainer.base_images_dir
filenames = [filename for filename in os.listdir(tzetlin_trainer.base_images_dir)]
dataset_dir = tzetlin_trainer.base_images_dir

# size=(512, 512)
threshold=128
img_array = []
for path in filenames:
    path = os.path.join(dataset_dir, path)
    img = Image.open(path).convert("L")          # grayscale
    # img = img.resize(size, Image.NEAREST)       # resize
    img_arr = np.array(img)
    bin_arr = (img_arr >= threshold).astype(np.uint8)
    img_array.append(bin_arr)

In [250]:
import pandas as pd

tzetlin_trainer.load_data()
df = tzetlin_trainer.lesion_df
df.head(1)

Loading lesion data...
Loaded 1061 lesion annotations


Unnamed: 0                           feedback_id                 user  \
0           0  490e3a64-32db-45ec-aa13-6a6718763fcc  lekandnow@gmail.com   

                              image_id                   timestamp  frame  \
0  12aw4ack71831bocuf5j3pz235kn1v361de  2023-12-23 17:14:50.958991     35   

                              lesion_id  lesion_frame  lesion_x  lesion_y  \
0  ca8b2bbe-6b6d-4c84-9e53-56f098d582c1          35.0     137.0     261.0   

   ...  lesion_trifurcation  lesion_trifurcationType lesion_bifurcation  \
0  ...                False                      NaN              False   

  lesion_bifurcationType lesion_bifurcationAngle lesion_aortoOstialStenosis  \
0                    NaN                     NaN                      False   

  lesion_occlusionLength lesion_heavyCalcification lesion_thrombus  \
0                   LT20                     False           False   

  lesion_severeTortuosity  
0                   False  

[1 rows x 31 columns]

In [100]:
df

Unnamed: 0                           feedback_id                 user  \
0              0  490e3a64-32db-45ec-aa13-6a6718763fcc  lekandnow@gmail.com   
1              1  b2b724db-f6ac-4e98-b208-87c420d0753a  lekandnow@gmail.com   
2              2  042f66bd-d3d1-4fb0-b339-727345afe47a  lekandnow@gmail.com   
3              3  04b3ae76-d9dc-4d07-babe-17e1dbd65f47  lekandnow@gmail.com   
4              4  09af7dfc-034c-4f89-919d-88363c0c8aa6  lekandnow@gmail.com   
...          ...                                   ...                  ...   
1056        1144  1ecaaa15-1f11-46c4-992c-e13af7d91718     sgurba@gmail.com   
1057        1145  1ecaaa15-1f11-46c4-992c-e13af7d91718     sgurba@gmail.com   
1058        1146  c969a559-636c-4379-9f15-47ca5c1bcca3     sgurba@gmail.com   
1059        1147  fb9a0ca3-5edf-4191-b7d4-6cb5ef40e723     sgurba@gmail.com   
1060        1148  fb9a0ca3-5edf-4191-b7d4-6cb5ef40e723     sgurba@gmail.com   

                                 image_id                   timestamp  frame  \
0     12aw4ack71831bocuf5j3pz235kn1v361de  2023-12-23 17:14:50.958991     35   
1      131aedfhs6pnf1fvtvp493iu1n6d1qnz22  2023-12-30 07:18:48.595050     30   
2      131aedfhs6pnf1fvtvp493iu1n8gd3gs22  2023-12-30 07:18:48.487550     23   
3      131aedfhs6pnf1fvtvp493iu1na8zz7s22  2023-12-30 07:18:48.773056     29   
4      131aedfhs6pnf1fvtvp493iu1nekk6h022  2023-12-30 07:18:48.993038     29   
...                                   ...                         ...    ...   
1056           13c2ur549vohc0jat2wqk9u231  2023-12-23 12:23:43.381127     35   
1057           13c2ur549vohc0jat2wqk9u231  2023-12-23 12:23:43.381127     35   
1058           13c2ur549vohc0jat2wqk9u4p1  2023-12-23 12:23:43.440082     19   
1059           13c2ur549vohc0jat2wqk9u6v1  2023-12-23 12:23:43.409926     16   
1060           13c2ur549vohc0jat2wqk9u6v1  2023-12-23 12:23:43.409926     16   

                                 lesion_id  lesion_frame  lesion_x  lesion_y  \
0     ca8b2bbe-6b6d-4c84-9e53-56f098d582c1          35.0     137.0     261.0   
1     21008078-1759-4d9b-b56b-88151c7a077b          30.0     128.0     135.0   
2     4712cf93-c404-4fb3-89ba-66225870bb3d          23.0     254.0     211.0   
3     f20650d1-ee08-42d9-be4e-dd5af8d10320          29.0     130.0     120.0   
4     6e2e2ad0-2403-44ea-9b44-2370eec3aa4d          29.0     233.0     400.0   
...                                    ...           ...       ...       ...   
1056  2ee857ea-87e2-4a3b-9873-80b71869715e          35.0       6.0     272.0   
1057  16020273-426f-4325-afbc-8d4fe61e1e39          35.0     263.0     380.0   
1058  62a49393-76e1-4119-aa2f-67edf4e65654          19.0     170.0     250.0   
1059  81666fab-83e7-41cc-be4f-e17b3107f2fe          16.0      95.0     266.0   
1060  c786471b-93bf-4c08-a16c-50b2d514a9fd          16.0     293.0     339.0   

      ...  lesion_trifurcation  lesion_trifurcationType lesion_bifurcation  \
0     ...                False                      NaN              False   
1     ...                False                      NaN              False   
2     ...                False                      NaN              False   
3     ...                False                      NaN              False   
4     ...                False                      NaN               True   
...   ...                  ...                      ...                ...   
1056  ...                False                      NaN              False   
1057  ...                False                      NaN              False   
1058  ...                False                      NaN              False   
1059  ...                False                      NaN              False   
1060  ...                False                      NaN              False   

     lesion_bifurcationType lesion_bifurcationAngle  \
0                       NaN                     NaN   
1                       NaN                     NaN   
2                       NaN      

In [251]:
count = df['lesion_width'].isna().sum()
count

np.int64(529)

In [112]:
len(np.where(df["lesion_x"].isna())[0])

529

In [269]:
df["lesion_id"].apply(lambda x: not pd.isna(x)).sum()

np.int64(532)

In [392]:
df[df["lesion_x"].apply(lambda x: pd.isna(x))]

Unnamed: 0                           feedback_id                 user  \
8              8  16d861ef-3ee9-46de-b95f-62819f821562  lekandnow@gmail.com   
10            10  1867a3bf-3014-4eab-8b48-5537e11bdbcb  lekandnow@gmail.com   
11            11  15121d9c-4066-4f63-b4a7-8051e559825b  lekandnow@gmail.com   
15            15  3ba69867-32e1-4cbd-b8e1-be61f9771345  lekandnow@gmail.com   
16            16  86e2785c-7fc0-4b57-88b5-d5645933ca8f  lekandnow@gmail.com   
...          ...                                   ...                  ...   
1138        1138  d72e0077-cc04-4d36-a5c5-0446d6763474     sgurba@gmail.com   
1139        1139  70ff46bb-5be7-4524-9935-a2fc4cf91778     sgurba@gmail.com   
1140        1140  2560349c-d557-4540-9e38-dfc1ff9ef792     sgurba@gmail.com   
1141        1141  959a1a20-7e85-453a-86e1-e057153a5ff0     sgurba@gmail.com   
1142        1142  72ad4f7b-c0ed-49bc-94fc-5f218d8ea11e     sgurba@gmail.com   

                                image_id                   timestamp  frame  \
8     131aedfhs6pnf1fvtvp498txzz8nvxst22  2023-04-09 09:06:35.159630     39   
10    131aedfhs6pnf1fvtvp498txzzhkoum022  2023-04-09 09:06:35.103741     32   
11    131aedfhs6pnf1fvtvp498txzzigu9a222  2023-05-11 14:34:00.584666     47   
15    131aedfhs6pnf1fvtvp498wvamq38ov722  2023-04-12 09:17:56.839061     37   
16    131aedfhs6pnf1fvtvp498wvamtxxej022  2023-04-12 09:17:56.859615     27   
...                                  ...                         ...    ...   
1138          13c2ur549vohc0jat2wd23mj71  2023-12-30 18:37:54.477035     18   
1139          13c2ur549vohc0jat2wd23mle1  2023-12-30 18:37:54.464485     19   
1140          13c2ur549vohc0jat2wqi9spx2  2023-12-23 12:23:43.356601     19   
1141          13c2ur549vohc0jat2wqi9syl1  2023-12-23 12:23:43.335069     11   
1142          13c2ur549vohc0jat2wqi9szw1  2023-12-23 12:23:43.433968     21   

     lesion_id  lesion_frame  lesion_x  lesion_y  ...  lesion_trifurcation  \
8          NaN           NaN       NaN       NaN  ...                  NaN   
10         NaN           NaN       NaN       NaN  ...                  NaN   
11         NaN           NaN       NaN       NaN  ...                  NaN   
15         NaN           NaN       NaN       NaN  ...                  NaN   
16         NaN           NaN       NaN       NaN  ...                  NaN   
...        ...           ...       ...       ...  ...                  ...   
1138       NaN           NaN       NaN       NaN  ...                  NaN   
1139       NaN           NaN       NaN       NaN  ...                  NaN   
1140       NaN           NaN       NaN       NaN  ...                  NaN   
1141       NaN           NaN       NaN       NaN  ...                  NaN   
1142       NaN           NaN       NaN       NaN  ...                  NaN   

      lesion_trifurcationType lesion_bifurcation lesion_bifurcationType  \
8                         NaN                NaN                    NaN   
10                        NaN                NaN                    NaN   
11                        NaN                NaN                    NaN   
15                        NaN                NaN                    NaN   
16                        NaN                NaN                    NaN   
...                       ...                ...                    ...   
1138                      NaN                NaN                    NaN   
1139                      NaN                NaN                    NaN   
1140                      NaN                NaN                    NaN   
1141                      NaN                NaN                    NaN   
1142                      NaN                NaN                    NaN   

     lesion_bifurcationAngle lesion_aortoOstialStenosis  \
8                        NaN                        NaN   
10                       NaN                        NaN   
11                       NaN                        NaN   
15                       NaN      

In [116]:
count = len(df[df['lesion_width'].isna()])
count

529

In [105]:
df.iloc[7]["lesion_x"]

np.float64(nan)

In [117]:
len(filenames)

931

In [122]:
len(lesion_filenames)

1061

In [103]:
np.where(df["lesion_x"].isna())

(array([   7,    9,   10,   12,   13,   14,   20,   37,   38,   39,   40,   41,   42,   43,   53,   54,   60,   61,   62,   63,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   85,   86,   87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   99,  100,  101,  102,  103,  104,  105,  106,  107,  108,
         109,  110,  111,  112,  113,  114,  115,  118,  119,  120,  121,  122,  123,  124,  125,  126,  127,  128,  129,  131,  132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  148,  149,  150,  151,  152,  153,  157,  158,  165,  166,  167,  183,  187,  205,  206,  212,  213,  217,  218,  219,  220,  221,
         222,  224,  227,  228,  229,  230,  238,  239,  241,  243,  244,  245,  247,  249,  251,  252,  253,  257,  258,  259,  260,  261,  262,  263,  264,  265,  269,  270,  271,  272,  273,  277,  278,  279,  280,  288,  295,  296,  298,  299,  300,  301,  302,  303,  304,  307,  320,  321,  322,  323,  324,  325,
         326,  329,  330,  334,  335,  3

In [125]:
df["image_id"].values

array(['12aw4ack71831bocuf5j3pz235kn1v361de', '131aedfhs6pnf1fvtvp493iu1n6d1qnz22', '131aedfhs6pnf1fvtvp493iu1n8gd3gs22', ..., '13c2ur549vohc0jat2wqk9u4p1', '13c2ur549vohc0jat2wqk9u6v1', '13c2ur549vohc0jat2wqk9u6v1'], shape=(1061,), dtype=object)

In [357]:
df = pd.read_csv("data/Dataset" + "/lesion_data.csv")

In [398]:
lesions_present_df = df[~df["lesion_width"].isna()]
lesions_present_df.shape

(620, 31)

In [393]:
lesions_present_df = df[~df["lesion_x"].isna()]
lesions_present_df.head(1)
# lesions_present_df.shape

Unnamed: 0                           feedback_id                 user  \
0           0  490e3a64-32db-45ec-aa13-6a6718763fcc  lekandnow@gmail.com   

                              image_id                   timestamp  frame  \
0  12aw4ack71831bocuf5j3pz235kn1v361de  2023-12-23 17:14:50.958991     35   

                              lesion_id  lesion_frame  lesion_x  lesion_y  \
0  ca8b2bbe-6b6d-4c84-9e53-56f098d582c1          35.0     137.0     261.0   

   ...  lesion_trifurcation  lesion_trifurcationType lesion_bifurcation  \
0  ...                False                      NaN              False   

  lesion_bifurcationType lesion_bifurcationAngle lesion_aortoOstialStenosis  \
0                    NaN                     NaN                      False   

  lesion_occlusionLength lesion_heavyCalcification lesion_thrombus  \
0                   LT20                     False           False   

  lesion_severeTortuosity  
0                   False  

[1 rows x 31 columns]

In [359]:
lesion_df_filenames = (lesions_present_df["image_id"].astype(str) + "_" + lesions_present_df["frame"].astype(str) + ".png").values
lesion_df_filenames_list = lesion_df_filenames.tolist()
lesion_df_filenames.shape
print(len(lesion_df_filenames_list))

620


In [360]:
# filenames_in_dir = 
filenames_in_dir = [filename for filename in os.listdir(tzetlin_trainer.base_images_dir)]
filenames_in_dir
len(filenames_in_dir)

931

In [361]:
df[~df["image_id"].isna()].shape

(1149, 31)

In [362]:
# All names are valid
filtered_df = df[df['image_id'].apply(lambda id: id is not np.nan and id is not None and id != "")]
filtered_df.shape

(1149, 31)

In [363]:
image_paths_df = (lesions_present_df["image_id"].astype(str) + "_" + lesions_present_df["frame"].astype(str) + ".png").values
image_paths_df_list = image_paths_df.tolist()
image_paths_df.shape

(620,)

In [364]:
image_paths_df_set = set(image_paths_df_list)
image_pathds_dir_set = set(filenames_in_dir)

intersection = image_paths_df_set.intersection(image_pathds_dir_set)
print(len(intersection))

393


In [188]:
len(image_paths_df_set - image_pathds_dir_set)

17

In [187]:
len(image_pathds_dir_set - image_paths_df_set)

583

In [189]:
len(image_pathds_dir_set | image_paths_df_set)

948

In [193]:
lesion_df_filenames.shape

(532,)

In [ ]:
# id_col = 4
# frame_col = 6
# lesion_filenames = []
# for el in df.itertuples():
#     img_id = el[id_col]
#     frame_id = el[frame_col]
#     lesion_frame = int(el[6])
#     lesion_x = el[9]
#     # if np.isnan(lesion_x):
#     #     print(lesion_x)
#     #     continue
#     lesion_width = el[7]
#     assert frame_id == lesion_frame
#     assert lesion_width is not None
#     img_filename = f"{img_id}_{lesion_frame}.png"
#     lesion_filenames.append(img_filename)

# Remove duplicates
# lesion_filenames = list(set(lesion_filenames))

In [80]:
# len(lesion_filenames)

1061

In [82]:
# lesion_filenames = list(set(lesion_filenames))
# print(len(lesion_filenames))

872


In [30]:
# df = pd.read_csv(tzetlin_trainer.lesion_data_path)
# Y_train = []
# for file_path, img in zip(filenames, img_array):
#     if file_path in lesion_filenames:
#         Y_train.append(1)
#     else:
#         Y_train.append(0)

# Y_train = np.array(Y_train)
# Y_train.shape

(931,)

In [378]:
def filename_to_bin_img_array(filename: str, size: tuple[int, int] | None = None, threshold: int = THRESHOLD) -> np.ndarray:
    # path = os.path.join(dataset_dir, filename)
    img = Image.open(filename).convert("L") # grayscale

    if size is not None:
        img = img.resize(size, Image.NEAREST) # resize

    img_arr = np.array(img)
    bin_arr = (img_arr >= threshold).astype(np.uint8)
    
    return bin_arr

def get_img_array(filenames: list[str], size: tuple[int, int] | None = None) -> list[np.ndarray]:
    img_array = []
    for filename in filenames:
        # try:
        #     bin_arr = filename_to_bin_img_array(filename, size)
        #     img_array.append(bin_arr)
        # except FileNotFoundError:
        #     print(f"Warning: file not found, skipping {filename}")
        #     continue
        # filename = os.path.join(dataset_dir, filename)
        bin_arr = filename_to_bin_img_array(filename, size)
        img_array.append(bin_arr)

    return img_array

def filter_uneven_shapes(img_array: list[np.ndarray], img_size_standard: tuple[int, int] = DEFAULT_IMG_SIZE, threshold: int = THRESHOLD) -> np.ndarray: # list[np.ndarray]:
    imgs_filtered = []
    for img in img_array:
        if img.shape != img_size_standard:
            print(f"Resizing img: {img.shape}")
            img = Image.fromarray(img*255)
            img = img.convert("L")          # grayscale
            img = img.resize(img_size_standard, Image.NEAREST)       # resize
            img_arr = np.array(img)
            bin_arr = (img_arr >= threshold).astype(np.uint8)
            imgs_filtered.append(bin_arr)
        else:
            imgs_filtered.append(img)
        
    imgs_filtered = np.array(imgs_filtered)
    
    return imgs_filtered

In [205]:
len(lesion_df_filenames_list)

532

In [212]:
len(lesion_df_filenames_list)

532

In [215]:
len(filenames_in_dir)

931

In [223]:
intersection = image_paths_df_set.intersection(image_pathds_dir_set)
filename_intersection_list = list(intersection)

In [ ]:
img_array = get_img_array([dataset_dir + "/" + filename for filename in filenames_in_dir])

In [233]:
print(len(set(filenames_in_dir).symmetric_difference(set(lesion_df_filenames_list))))

600


In [351]:
Y_train = []
for file_path, img in zip(filenames_in_dir, img_array):
    if file_path in lesion_df_filenames_list:
        Y_train.append(1)
    else:
        Y_train.append(0)

Y_train = np.array(Y_train)
Y_train.shape

(931,)

In [279]:
img_size = (512, 512)

imgs_filtered = []
for img in img_array:
    if img.shape != img_size:
        print(f"Resizing img: {img.shape}")
        img = Image.fromarray(img*255)
        img = img.convert("L")          # grayscale
        img = img.resize(img_size, Image.NEAREST)       # resize
        img_arr = np.array(img)
        bin_arr = (img_arr >= threshold).astype(np.uint8)
        imgs_filtered.append(bin_arr)
    else:
        imgs_filtered.append(img)
    
imgs_filtered = np.array(imgs_filtered)
imgs_filtered.shape

Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)


(931, 512, 512)

In [239]:
# imgs_filtered = np.array([img.reshape(img_size[0] * img_size[1]) for img in imgs_filtered])
imgs_filtered

array([[[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 1, 0, 1],
        [0, 0, 0, ..., 0, 0, 1]],

       [[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 

In [ ]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(60000, 784))

In [ ]:
Y_train.shape

(931,)

In [365]:
import os

directory = "data/Dataset/base_images"

# get all files ending with .png
png_files = [f for f in os.listdir(directory) if f.endswith(".png")]

# optionally get full paths
png_paths = [f for f in png_files]

print(png_paths)
filenames_in_dir = png_paths

['131aedfhs6pnf1fvtvp49mldx9653nxv22_45.png', '131aedfhs6pnf1fvtvp49jyuzi7s8bi722_25.png', '131aedfhs6pnf1fvtvp493b3tui4y3s122_31.png', '131aedfhs6pnf1fvtvp49jxos89wxpbw22_38.png', '131aedfhs6pnf1fvtvp49mmdojib5fd822_38.png', '13c2ur5452xb62wphbkenx73hk0ymr4i_13.png', '131aedfhs6pnf1fvtvp49ee0uljalbqq22_34.png', '131aedfhs6pnf1fvtvp49eatmwrhr2rq22_37.png', '131aedfhs6pnf1fvtvp49mff2pm7g60u22_48.png', '131aedfhs6pnf1fvtvp49h4bhdjeabmt22_31.png', '131aedfhs6pnf1fvtvp49mjbhcpprubf22_23.png', '131aedfhs6pnf1fvtvp49mia86wgzqqd22_31.png', '131aedfhs6pnf1fvtvp49mg8hvxr9qia22_35.png', '131aedfhs6pnf1fvtvp49ee0uli12bvs22_33.png', '131aedfhs6pnf1fvtvp498txzzhkoum022_32.png', '131aedfhs6pnf1fvtvp49jto5drpmy7a22_25.png', '131aedfhs6pnf1fvtvp49mif6sem5a5q22_45.png', '131aedfhs6pnf1fvtvp49mlbqwqy6eyr22_32.png', '131aedfhs6pnf1fvtvp49mj6h8sfw4ib22_26.png', '12nc2fo32bddqwoyhtlmwecxrf3rzr1ft217_51.png', '131aedfhs6pnf1fvtvp49jxos89bhfmq22_21.png', '131aedfhs6pnf1fvtvp49mmdojgwb78y22_36.png', '131aedfh

In [341]:
len(filenames_in_dir)

931

In [339]:
filenames_not_present_in_lesion_df = list(set(filenames_in_dir) - set(lesion_df_filenames_list))
len(filenames_not_present_in_lesion_df)

583

In [346]:
dataset_dir_or = "data/Dataset/base_images"

In [380]:
img_array = get_img_array([dataset_dir_or + "/" + f for f in filenames_in_dir])
img_array

[array([[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 1, 0, 1],
        [0, 0, 0, ..., 0, 0, 1]], shape=(512, 512), dtype=uint8),
 array([[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]], shape=(512, 512), dtype=uint8),
 array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]], shape=(512, 512), dtype=uint8),
 array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 1]], shape=(512, 512), dtype=uint8),
 array([[0, 1, 0, ..., 0

In [381]:
len(img_array)

931

In [382]:
imgs_filtered = filter_uneven_shapes(img_array)

Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)


In [383]:
len(imgs_filtered)

931

In [371]:
len(lesion_df_filenames_list)

620

In [384]:
Y_train = []
for file_path, img in zip(filenames_in_dir, img_array):
    if file_path in lesion_df_filenames_list:
        Y_train.append(1)
    else:
        Y_train.append(0)

Y_train = np.array(Y_train)
Y_train.shape

(931,)

In [373]:
imgs_filtered.shape

(3959, 512, 512)

In [379]:
img_array_not = get_img_array([dataset_dir + "/" + filename for filename in filenames_not_present_in_lesion_df])

In [319]:
imgs_filtered = filter_uneven_shapes(img_array_not)
imgs_filtered.shape

Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)
Resizing img: (1016, 1016)


(583, 512, 512)

In [ ]:
Y_train =

In [385]:
lesion_trainer = LesionTzetlinTrainer()
# dataset_dir = lesion_trainer.base_images_dir          # change to your dataset path
# img_size = (28,28)               # you can change this
# X, y, class_to_idx = load_image_folder(dataset_dir, size=img_size)
# print("Loaded", X.shape, "labels:", np.unique(y))

# train/test split
X = imgs_filtered
y = Y_train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Convert to types expected by pyTsetlinMachine (0/1 uint8)
X_train = X_train.astype(np.uint8)
X_test  = X_test.astype(np.uint8)

In [386]:
X_train

array([[[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 0, ..., 1, 1, 1],
        [1, 1, 0, ..., 1, 1, 1],
        [1, 1, 0, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 1]],

       ...,

       [[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 

In [35]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 

In [387]:
# instantiate Convolutional TM
# number_of_clauses, T, s, patch_dim
# tm = MultiClassConvolutionalTsetlinMachine2D(number_of_clauses=2000,
#                                                 T=50*100,   # adjust
#                                                 s=5.0,
#                                                 patch_dim=(8,8),
#                                                 weighted_clauses=True)

tm = MultiClassTsetlinMachine(number_of_clauses=2000,
                                                T=50*100,   # adjust
                                                s=5.0,
                                                # patch_dim=(8,8),
                                                weighted_clauses=True)

# train
epochs = 200
t0 = time()
tm.fit(X_train, y_train, epochs=epochs)
t1 = time()
print(f"Training done in {t1-t0:.1f}s")

Training done in 51.3s


In [388]:
# predict & evaluate
y_pred = tm.predict(X_test)
acc = np.mean(y_pred == y_test)
print(f"Test accuracy: {acc*100:.2f}%")

# save state (optional)
state = tm.get_state()   # you can later set_state(state)
print("Saved TM state (length):", len(state))


Test accuracy: 50.27%
Saved TM state (length): 2


In [389]:
y_pred = tm.predict(imgs_filtered)

In [390]:
# y = np.array([0]*len(filenames_not_present_in_lesion_df))
# y

In [391]:
np.mean(y_pred == y)

np.float64(0.5091299677765844)

In [330]:
df.head(1)

Unnamed: 0                           feedback_id                 user  \
0           0  490e3a64-32db-45ec-aa13-6a6718763fcc  lekandnow@gmail.com   

                              image_id                   timestamp  frame  \
0  12aw4ack71831bocuf5j3pz235kn1v361de  2023-12-23 17:14:50.958991     35   

                              lesion_id  lesion_frame  lesion_x  lesion_y  \
0  ca8b2bbe-6b6d-4c84-9e53-56f098d582c1          35.0     137.0     261.0   

   ...  lesion_trifurcation  lesion_trifurcationType lesion_bifurcation  \
0  ...                False                      NaN              False   

  lesion_bifurcationType lesion_bifurcationAngle lesion_aortoOstialStenosis  \
0                    NaN                     NaN                      False   

  lesion_occlusionLength lesion_heavyCalcification lesion_thrombus  \
0                   LT20                     False           False   

  lesion_severeTortuosity  
0                   False  

[1 rows x 31 columns]

NameError: name 'lesion_df' is not defined

In [30]:
from pyTsetlinMachine.tm import MultiClassTsetlinMachine